name: Main
on:
  push:
    branches:
      - main

jobs:
  deploy_to_firebase:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build-storybook
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_UI_NINJABUNNY_DEV }}"
